import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'

import PythonSourceEditor from '@/components/workstation/PythonSourceEditor.vue'

describe('PythonSourceEditor', () => {
  it('offers context-aware unified SDK suggestions and inserts the selected expression', async () => {
    const wrapper = mount(PythonSourceEditor, { props: { modelValue: '', ariaLabel: 'Python source' } })
    const editor = wrapper.find('[aria-label="Python source"]')
    await wrapper.setProps({ modelValue: 'market.' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(7, 7)
    ;(editor.element as HTMLTextAreaElement).focus()
    await editor.trigger('keyup')
    expect(editor.element.tagName).toBe('TEXTAREA')
    expect(editor.attributes('role')).toBeUndefined()
    expect(editor.attributes('aria-autocomplete')).toBe('list')
    expect(editor.attributes('aria-haspopup')).toBe('listbox')
    expect(editor.attributes('aria-expanded')).toBe('true')
    expect(editor.attributes('aria-controls')).toBeTruthy()
    expect(editor.attributes('aria-activedescendant')).toBeTruthy()
    expect(wrapper.find(`#${editor.attributes('aria-controls')}`).attributes('role')).toBe('listbox')
    expect(wrapper.find(`#${editor.attributes('aria-activedescendant')}`).attributes('role')).toBe('option')
    expect(wrapper.find('[aria-label="Python source SDK suggestions"]').exists()).toBe(true)
    expect(wrapper.text()).toContain('market.close()')
    expect(wrapper.get('[role="status"]').text()).toContain('SDK suggestions')
    expect(wrapper.get('[role="status"]').text()).toContain('market.close() selected')
    await wrapper.find('[aria-label="Python source SDK suggestions"] button').trigger('mousedown')
    const nextValue = wrapper.emitted('update:modelValue')?.at(-1)?.[0]
    expect(nextValue).toBe('market.close()')
    await wrapper.setProps({ modelValue: nextValue })
    expect((editor.element as HTMLTextAreaElement).value).toContain('market.close()')
  })

  it('normalizes line endings and trailing whitespace without changing code semantics', async () => {
    const wrapper = mount(PythonSourceEditor, { props: { modelValue: 'x = 1  \r\n\r\n', ariaLabel: 'Python source' } })
    await wrapper.find('[aria-label="Normalize Python source"]').trigger('click')
    expect(wrapper.emitted('update:modelValue')?.at(-1)?.[0]).toBe('x = 1\n')
  })

  it('supports keyboard selection and completion without stealing editor navigation when suggestions are closed', async () => {
    const wrapper = mount(PythonSourceEditor, { props: { modelValue: 'market.', ariaLabel: 'Python source' } })
    const editor = wrapper.find('[aria-label="Python source"]')
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(7, 7)
    ;(editor.element as HTMLTextAreaElement).focus()
    await editor.trigger('keyup')
    const firstSuggestionId = editor.attributes('aria-activedescendant')
    expect(firstSuggestionId).toBeTruthy()
    expect(wrapper.find(`#${firstSuggestionId}`).attributes('aria-selected')).toBe('true')

    await editor.trigger('keydown', { key: 'ArrowDown' })
    const secondSuggestionId = editor.attributes('aria-activedescendant')
    expect(secondSuggestionId).toBeTruthy()
    expect(secondSuggestionId).not.toBe(firstSuggestionId)
    expect(wrapper.find(`#${secondSuggestionId}`).attributes('aria-selected')).toBe('true')
    expect(wrapper.get('[role="status"]').text()).toContain('market.open() selected')
    await editor.trigger('keydown', { key: 'Enter' })
    expect(wrapper.emitted('update:modelValue')?.at(-1)?.[0]).toBe('market.open()')

    await editor.trigger('keydown', { key: 'Escape' })
    expect(wrapper.find('[role="listbox"]').exists()).toBe(false)
    expect(editor.attributes('aria-expanded')).toBe('false')
    expect(editor.attributes('aria-controls')).toBeUndefined()
  })

  it('keeps suggestion popup identifiers unique across linked editor instances', async () => {
    const first = mount(PythonSourceEditor, { props: { modelValue: 'market.', ariaLabel: 'Python source' } })
    const second = mount(PythonSourceEditor, { props: { modelValue: 'market.', ariaLabel: 'Python source' } })
    await first.find('textarea').trigger('focus')
    await first.find('textarea').trigger('keyup')
    await second.find('textarea').trigger('focus')
    await second.find('textarea').trigger('keyup')
    const firstId = first.find('textarea').attributes('aria-controls')
    const secondId = second.find('textarea').attributes('aria-controls')
    expect(firstId).toBeTruthy()
    expect(secondId).toBeTruthy()
    expect(firstId).not.toBe(secondId)
    const firstOptionId = first.find('textarea').attributes('aria-activedescendant')
    const secondOptionId = second.find('textarea').attributes('aria-activedescendant')
    expect(firstOptionId).toBeTruthy()
    expect(secondOptionId).toBeTruthy()
    expect(firstOptionId).not.toBe(secondOptionId)
    first.unmount()
    second.unmount()
  })

  it('exposes the complete supported SDK surface through prefix filtering', async () => {
    const wrapper = mount(PythonSourceEditor, { props: { modelValue: 'market.benchmark_', ariaLabel: 'Python source' } })
    const editor = wrapper.find('[aria-label="Python source"]')
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(17, 17)
    await editor.trigger('focus')
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('market.benchmark_close()')
    await wrapper.setProps({ modelValue: 'market.benchmark_m' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(19, 19)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('market.benchmark_metadata()')

    await wrapper.setProps({ modelValue: 'ta.' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(3, 3)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain("ta.indicator('rsi', {'period': 14})")
    expect(wrapper.text()).toContain('ta.ema(market.close(), 20)')
    expect(wrapper.text()).not.toContain('ta.atr(')

    await wrapper.setProps({ modelValue: 'stats.' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(6, 6)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('stats.mean(values)')
    expect(wrapper.text()).toContain("stats.streaks(values, 'positive')")
    expect(wrapper.text()).toContain('stats.percentile(values, 0.9)')
    await wrapper.setProps({ modelValue: 'stats.d' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(8, 8)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('stats.distribution(values, 8, current)')
    await wrapper.setProps({ modelValue: 'research.' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(9, 9)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('research.conditional_outcomes(dataset, indices, [1, 5, 20])')
    expect(wrapper.text()).toContain('research.regimes(dataset, 20, 0.05)')
    await wrapper.setProps({ modelValue: 'research.h' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(10, 10)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('research.historical_comparison(values, current)')
    await wrapper.setProps({ modelValue: 'research.b' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(10, 10)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain('research.breadth_thrust(dataset, 90)')
    expect(wrapper.text()).toContain('research.breadth_thrust_history(dataset, 90)')

    await wrapper.setProps({ modelValue: 'output.' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(7, 7)
    await editor.trigger('keyup')
    await wrapper.setProps({ modelValue: 'output.h' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(8, 8)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain("output.heatmap('name', values, rows, columns)")
    await wrapper.setProps({ modelValue: 'output.d' })
    ;(editor.element as HTMLTextAreaElement).setSelectionRange(8, 8)
    await editor.trigger('keyup')
    expect(wrapper.text()).toContain("output.dashboard('name', [{'artifact': 'series'}])")
  })
})
