"""initial_schema

Revision ID: 030fc5ddfae4
Revises:
Create Date: 2026-03-17 22:28:40.041616

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "030fc5ddfae4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


timeframe_enum = postgresql.ENUM(
    "M1", "M5", "M15", "M30", "H1", "H2", "H4", "H12", "D1", "W1", "MN",
    name="timeframe",
    create_type=False,
)
alert_status_enum = postgresql.ENUM(
    "ACTIVE", "TRIGGERED", "PAUSED", "EXPIRED",
    name="alertstatus",
    create_type=False,
)
option_right_enum = postgresql.ENUM(
    "CALL", "PUT",
    name="optionright",
    create_type=False,
)
option_style_enum = postgresql.ENUM(
    "AMERICAN", "EUROPEAN", "BERMUDAN",
    name="optionstyle",
    create_type=False,
)
alert_condition_enum = postgresql.ENUM(
    "CROSSES_ABOVE", "CROSSES_BELOW", "TOUCHES", "PERCENT_CHANGE_UP", "PERCENT_CHANGE_DOWN",
    name="alertcondition",
    create_type=False,
)


def _create_enum_if_missing(name: str, values: tuple[str, ...]) -> None:
    quoted_values = ", ".join(f"'{value}'" for value in values)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE t.typname = '{name}'
                  AND n.nspname = current_schema()
            ) THEN
                EXECUTE format($ddl$CREATE TYPE %I AS ENUM ({quoted_values})$ddl$, '{name}');
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_enum_if_missing("timeframe", ("M1", "M5", "M15", "M30", "H1", "H2", "H4", "H12", "D1", "W1", "MN"))
    _create_enum_if_missing("alertstatus", ("ACTIVE", "TRIGGERED", "PAUSED", "EXPIRED"))
    _create_enum_if_missing("optionright", ("CALL", "PUT"))
    _create_enum_if_missing("optionstyle", ("AMERICAN", "EUROPEAN", "BERMUDAN"))
    _create_enum_if_missing(
        "alertcondition",
        ("CROSSES_ABOVE", "CROSSES_BELOW", "TOUCHES", "PERCENT_CHANGE_UP", "PERCENT_CHANGE_DOWN"),
    )
    op.create_table('asset_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mic', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('market_open', sa.String(length=5), nullable=True),
    sa.Column('market_close', sa.String(length=5), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_mic'), 'exchange', ['mic'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('indicator_preset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_preset_user_id'), 'indicator_preset', ['user_id'], unique=False)
    op.create_table('instrument_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_class_id'], ['asset_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_type_asset_class_id'), 'instrument_type', ['asset_class_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrument_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_instrument_type_id'), 'instrument', ['instrument_type_id'], unique=False)
    op.create_index(op.f('ix_instrument_symbol'), 'instrument', ['symbol'], unique=False)
    op.create_table('screener_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('universe_type', sa.String(length=20), nullable=False),
    sa.Column('universe_watchlist_id', sa.Integer(), nullable=True),
    sa.Column('universe_asset_class_id', sa.Integer(), nullable=True),
    sa.Column('universe_instrument_ids', sa.JSON(), nullable=True),
    sa.Column('timeframe', timeframe_enum, nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universe_asset_class_id'], ['asset_class.id'], ),
    sa.ForeignKeyConstraint(['universe_watchlist_id'], ['watchlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_definition_user_id'), 'screener_definition', ['user_id'], unique=False)
    op.create_table('chart_drawing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', timeframe_enum, nullable=True),
    sa.Column('pin_to_all', sa.Boolean(), nullable=False),
    sa.Column('drawing_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_drawing_instrument_id'), 'chart_drawing', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_chart_drawing_timeframe'), 'chart_drawing', ['timeframe'], unique=False)
    op.create_index(op.f('ix_chart_drawing_user_id'), 'chart_drawing', ['user_id'], unique=False)
    op.create_table('equity_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('exchange_mic', sa.String(length=10), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('market_cap_tier', sa.String(length=10), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('forex_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('pip_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('future_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('underlying_name', sa.String(length=200), nullable=True),
    sa.Column('underlying_instrument_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tick_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('settlement_type', sa.String(length=20), nullable=True),
    sa.Column('first_notice_date', sa.Date(), nullable=True),
    sa.Column('last_trading_date', sa.Date(), nullable=True),
    sa.Column('is_continuous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['underlying_instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('indicator_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', timeframe_enum, nullable=False),
    sa.Column('indicator_a_type', sa.String(length=30), nullable=False),
    sa.Column('indicator_a_params', sa.JSON(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('indicator_b_type', sa.String(length=30), nullable=True),
    sa.Column('indicator_b_params', sa.JSON(), nullable=True),
    sa.Column('status', alert_status_enum, nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_value_a', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_value_b', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_notification_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_alert_instrument_id'), 'indicator_alert', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_indicator_alert_status'), 'indicator_alert', ['status'], unique=False)
    op.create_index(op.f('ix_indicator_alert_user_id'), 'indicator_alert', ['user_id'], unique=False)
    op.create_table('instrument_listing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_listing_exchange_id'), 'instrument_listing', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_instrument_listing_instrument_id'), 'instrument_listing', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_instrument_listing_ticker'), 'instrument_listing', ['ticker'], unique=False)
    op.create_table('ohlcv_bar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', timeframe_enum, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ohlcv_instrument_tf_ts', 'ohlcv_bar', ['instrument_id', 'timeframe', 'ts'], unique=False)
    op.create_index('uq_ohlcv_bar', 'ohlcv_bar', ['instrument_id', 'timeframe', 'ts', 'is_adjusted'], unique=True)
    op.create_table('option_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('underlying_instrument_id', sa.Integer(), nullable=False),
    sa.Column('right', option_right_enum, nullable=False),
    sa.Column('style', option_style_enum, nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('implied_vol', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['underlying_instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_index(op.f('ix_option_detail_underlying_instrument_id'), 'option_detail', ['underlying_instrument_id'], unique=False)
    op.create_table('price_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('condition', alert_condition_enum, nullable=False),
    sa.Column('threshold_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', alert_status_enum, nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_known_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_notification_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alert_instrument_id'), 'price_alert', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_price_alert_status'), 'price_alert', ['status'], unique=False)
    op.create_index(op.f('ix_price_alert_user_id'), 'price_alert', ['user_id'], unique=False)
    op.create_table('screener_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screener_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('matched_ids', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['screener_id'], ['screener_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_result_screener_id'), 'screener_result', ['screener_id'], unique=False)
    op.create_table('watchlist_instrument',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'instrument_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_instrument')
    op.drop_index(op.f('ix_screener_result_screener_id'), table_name='screener_result')
    op.drop_table('screener_result')
    op.drop_index(op.f('ix_price_alert_user_id'), table_name='price_alert')
    op.drop_index(op.f('ix_price_alert_status'), table_name='price_alert')
    op.drop_index(op.f('ix_price_alert_instrument_id'), table_name='price_alert')
    op.drop_table('price_alert')
    op.drop_index(op.f('ix_option_detail_underlying_instrument_id'), table_name='option_detail')
    op.drop_table('option_detail')
    op.drop_index('uq_ohlcv_bar', table_name='ohlcv_bar')
    op.drop_index('ix_ohlcv_instrument_tf_ts', table_name='ohlcv_bar')
    op.drop_table('ohlcv_bar')
    op.drop_index(op.f('ix_instrument_listing_ticker'), table_name='instrument_listing')
    op.drop_index(op.f('ix_instrument_listing_instrument_id'), table_name='instrument_listing')
    op.drop_index(op.f('ix_instrument_listing_exchange_id'), table_name='instrument_listing')
    op.drop_table('instrument_listing')
    op.drop_index(op.f('ix_indicator_alert_user_id'), table_name='indicator_alert')
    op.drop_index(op.f('ix_indicator_alert_status'), table_name='indicator_alert')
    op.drop_index(op.f('ix_indicator_alert_instrument_id'), table_name='indicator_alert')
    op.drop_table('indicator_alert')
    op.drop_table('future_detail')
    op.drop_table('forex_detail')
    op.drop_table('equity_detail')
    op.drop_index(op.f('ix_chart_drawing_user_id'), table_name='chart_drawing')
    op.drop_index(op.f('ix_chart_drawing_timeframe'), table_name='chart_drawing')
    op.drop_index(op.f('ix_chart_drawing_instrument_id'), table_name='chart_drawing')
    op.drop_table('chart_drawing')
    op.drop_index(op.f('ix_screener_definition_user_id'), table_name='screener_definition')
    op.drop_table('screener_definition')
    op.drop_index(op.f('ix_instrument_symbol'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_instrument_type_id'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_instrument_type_asset_class_id'), table_name='instrument_type')
    op.drop_table('instrument_type')
    op.drop_index(op.f('ix_indicator_preset_user_id'), table_name='indicator_preset')
    op.drop_table('indicator_preset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_exchange_mic'), table_name='exchange')
    op.drop_table('exchange')
    op.drop_table('data_source')
    op.drop_table('asset_class')
    bind = op.get_bind()
    alert_condition_enum.drop(bind, checkfirst=True)
    option_style_enum.drop(bind, checkfirst=True)
    option_right_enum.drop(bind, checkfirst=True)
    alert_status_enum.drop(bind, checkfirst=True)
    bind = op.get_bind()
    timeframe_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
