"""price_alert_add_price_field_within_percent

Revision ID: 87505586ba42
Revises: 9d802b701062
Create Date: 2026-03-28 23:02:08.795716

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '87505586ba42'
down_revision: Union[str, None] = '9d802b701062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
