"""price_alert_price_field_within_percent

Revision ID: 9d802b701062
Revises: a3a03047acc3
Create Date: 2026-03-28 22:49:19.820858

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9d802b701062'
down_revision: Union[str, None] = 'a3a03047acc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alert', sa.Column('price_field', sa.String(length=10), nullable=False))
    op.add_column('price_alert', sa.Column('within_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alert', 'within_percent')
    op.drop_column('price_alert', 'price_field')
    # ### end Alembic commands ###
