"""add_instrument_indicator_config

Revision ID: a3a03047acc3
Revises: 030fc5ddfae4
Create Date: 2026-03-27 23:29:52.153656

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a3a03047acc3'
down_revision: Union[str, None] = '030fc5ddfae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
