"""widen_equity_detail_country

Revision ID: bd0f77f63cac
Revises: 
Create Date: 2026-03-15 09:10:53.979004

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bd0f77f63cac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equity_detail', 'country',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equity_detail', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###
